# Generated by Django 6.0.2 on 2026-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_city_state_trip_transport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='transport_type',
            field=models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('RTC', 'RTC Bus')], default='BUS', max_length=10),
        ),
    ]
