# Generated by Django 6.0.2 on 2026-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='transport_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Train'), ('FLIGHT', 'Flight')], max_length=10),
        ),
    ]
